//
// Created by alunos on 07/10/2025.
//

#ifndef PRODUTORA_EVENTOS_ALG_II_UTILS_VALIDACOES_H
#define PRODUTORA_EVENTOS_ALG_II_UTILS_VALIDACOES_H

#endif //PRODUTORA_EVENTOS_ALG_II_UTILS_VALIDACOES_H